POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John1",
  "lastName": "Doe1",
  "email": "john242344@doe.com",
  "password": "@Password123"
}

###
POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization:

{
  "users": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "email": "john112@doe.com",
      "password": "@Password123"
    }
  ]
}