POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John1",
  "lastName": "Doe1",
  "email": "john1110@doe.com",
  "password": "@Password123"
}

###
POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoiam9objEwQGRvZS5jb20iLCJpYXQiOjE3MzU2MzIzNTMsImV4cCI6MTczNTYzNTk1MywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.fTAyEMIOA-Ta3dQk-bPjmoP5fon-dyrKFCmVx8Q54qE

{
  "users": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "email": "john112@doe.com",
      "password": "@Password123"
    }
  ]
}