POST localhost:3000/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoiam9objEwQGRvZS5jb20iLCJpYXQiOjE3MzU3MTMzNjYsImV4cCI6MTczNTcxNjk2NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.2ro7S3W82_7GxTfat6LN8_dtVB6CnqyJ8gUxk3Wg4b4

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTczNTcxMzM2NiwiZXhwIjoxNzM1Nzk5NzY2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.LaypSnaXi3KSd6J6gBLKV-NIQOldhHWThqbUCUp5Kwo"
}
